### ISSUE TITLE
NullPointerException in Python3 grammar

### ISSUE THREAD

**Issue by maiermic** [antlr/grammars-v4#113]
Hi,
I recognized a little bug in the Python3 grammar.

Code:

``` java
public static void main(String[] args) {
    String input = "def func():\n  if";

    ANTLRInputStream source = new ANTLRInputStream(input);
    Python3Lexer lexer = new Python3Lexer(source);
    CommonTokenStream tokens = new CommonTokenStream(lexer);
    Python3Parser parser = new Python3Parser(tokens);

    Python3Parser.File_inputContext tree = parser.file_input();
}
```

Expected:

```
line 0:-1 no viable alternative at input '\n'
```

Got:

```
line 0:-1 no viable alternative at input '\n'

Exception in thread "main" java.lang.NullPointerException
    at org.antlr.v4.runtime.DefaultErrorStrategy.getMissingSymbol(DefaultErrorStrategy.java:591)
    at org.antlr.v4.runtime.DefaultErrorStrategy.recoverInline(DefaultErrorStrategy.java:477)
    at org.antlr.v4.runtime.Parser.match(Parser.java:223)
    at python.Python3Parser.if_stmt(Python3Parser.java:2959)
    at python.Python3Parser.compound_stmt(Python3Parser.java:2857)
    at python.Python3Parser.stmt(Python3Parser.java:1253)
    at python.Python3Parser.suite(Python3Parser.java:3488)
    at python.Python3Parser.funcdef(Python3Parser.java:600)
    at python.Python3Parser.compound_stmt(Python3Parser.java:2887)
    at python.Python3Parser.stmt(Python3Parser.java:1253)
    at python.Python3Parser.file_input(Python3Parser.java:296)
    at python.PythonMain.main(PythonMain.java:24)
```

Best regards,
Michael

**Comment by DOC1207** [comment]
where find Python3Parser.java?

**Comment by bkiers** [comment]
@DOC1207 it will be generated by ANTLR's `Tool` clas. More information about this, see: https://github.com/antlr/antlr4/blob/master/doc/getting-started.md
