### ISSUE TITLE
Unable to parse try-with-resources in java9 

### ISSUE THREAD

**Issue by artemmalykh** [antlr/grammars-v4#1135]
I am trying to parse this class
```
public class A {
    private void test(X x) {
        try (Y ch = open()) {
             ;
        }
    }
}
```
with parser generated by java9 grammar, here is the code:
```
File file = new File(this.getClass().getResource("../../../../testclasses/TWR.java").getFile());

Java9Lexer lexer = new Java9Lexer(CharStreams.fromStream(new FileInputStream(file)));
CommonTokenStream tokens = new CommonTokenStream(lexer);
Java9Parser parser = new Java9Parser(tokens);
parser.setErrorHandler(new DefaultErrorStrategy() {
            @Override
            protected void reportInputMismatch(Parser recognizer,
                                               InputMismatchException e)  {
                throw new IllegalArgumentException(e);
            }
        });
ParseTree tree = parser.compilationUnit();
```
and get stacktrace with such top entries:

**java.lang.IllegalArgumentException: org.antlr.v4.runtime.InputMismatchException
    at com.mycompany.ASTReduceTest$1.reportInputMismatch(ASTReduceTest.java:53)
    at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:139)
    at com.mycompany.parser.antlr.Java9Parser.lambdaExpression(Java9Parser.java:16953)
    at com.mycompany.parser.antlr.Java9Parser.expression(Java9Parser.java:16888)
    at com.mycompany.parser.antlr.Java9Parser.resource(Java9Parser.java:12975)
    at com.mycompany.parser.antlr.Java9Parser.resourceList(Java9Parser.java:12873)
    at com.mycompany.parser.antlr.Java9Parser.resourceSpecification(Java9Parser.java:12813)
    at com.mycompany.parser.antlr.Java9Parser.tryWithResourcesStatement(Java9Parser.java:12744)**

**Comment by dmitrievanthony** [comment]
It looks like the core cause of your problem is using of the word 'open' in the example. Java9 grammars had not been processing it correctly until recently, but as far as I see @JanUlrich has already fixed it in these two commits ([40b3fea](https://github.com/antlr/grammars-v4/commit/40b3feab9242596f9b249f5ee6a684ec78ae380d#diff-ea07d56fad4aa395e64ef73280bd3da7), [85af073](https://github.com/antlr/grammars-v4/commit/85af073046ab4d610554a05c5b09bc909aacbaab#diff-ea07d56fad4aa395e64ef73280bd3da7)).
