### ISSUE TITLE
Python3-JS fails in lexer step when run

### ISSUE THREAD

**Issue by simerlec** [antlr/grammars-v4#1801]
Hello 👋 

tried to use the [python3-js grammar](https://github.com/antlr/grammars-v4/tree/master/python/python3-js) and apparently it fails at the lexing step when used. Generated the needed files from the grammar with `-Dlanguage=JavaScript`, then tried to use it with this codesnippet which is pretty straighforward and basically just what is explained in the docs/book:

```
const antlr4 = require("antlr4");
const Python3Lexer = require("./Python3Lexer").Python3Lexer;
const Python3Parser = require("./Python3Parser").Python3Parser;

...
var chars = new antlr4.InputStream(input);
var lexer = new Python3Lexer(chars);
var commonTokenStream = new antlr4.CommonTokenStream(lexer);
var parser = new Python3Parser(commonTokenStream);
parser.buildParseTrees = true;
const tree = parser.file_input();
```

which leads to

```
TypeError: this.atStartOfInput is not a function
    at Python3Lexer.NEWLINE_sempred (/python-autocomplete-node/Python3Lexer.js:1298:19)
    at Python3Lexer.sempred (/python-autocomplete-node/Python3Lexer.js:1289:19)
    ...
```

What can I do to make this work? Apparently @sonny3690 already noticed that it's not working out-of-the-box as mentioned here https://github.com/antlr/grammars-v4/pull/1764

thanks 🙏

**Comment by sonny3690** [comment]
The Python3-JS Grammar has issues around the Lexer Members. It's just syntactically incorrect, and I'm presuming that someone wrote it on the go and didn't properly test the generated lexer. I think though that the overall logic is probably right since it appears that someone just copied over the member rules from another language.

I'll try to get a fix up if I have time, but can't guarantee (sorry :(). This issue prompted me to actually write the Python-TS grammar, which you can use if you have the bandwidth to migrate to TS.

**Comment by sonny3690** [comment]
On a side note, I've also noticed a few other issues around lexing/parsing in Python. I'm actually not sure Python's grammar can be completely captured by ANTLR grammar, (even the Java target's grammar, which presumably is most up-to-date, has a couple problems).


If you're looking for a perfect solution, you might be better off just using the Python Compiler itself and transpiling the output.

**Comment by simerlec** [comment]
Thanks for the response @sonny3690 

One thought I had, which i hadn't had the chance to try yet was to just use your working Python-TS grammar, generate the needed files and simply transpile them to JS. Should work as well if I fix some of the imports, right?
