### ISSUE TITLE
Ecmascript grammar does not parse getters/setters

### ISSUE THREAD

**Issue by renatahodovan** [antlr/grammars-v4#214]
Given a the following javascript source:

``` javascript
a = {
    get b() {}
}
```

When trying to parse this with https://github.com/antlr/grammars-v4/blob/master/ecmascript/ECMAScript.g4 it results in a no viable alternative error.

If BailErrorStrategy is set then it shows that the fail comes from the ParserATNSimulator:

``` javascript
line 2:8 no viable alternative at input 'get b'
Exception in thread "main" org.antlr.v4.runtime.misc.ParseCancellationException
    at org.antlr.v4.runtime.BailErrorStrategy.recover(BailErrorStrategy.java:75)
    at ECMAScriptParser.propertyAssignment(ECMAScriptParser.java:2781)
    at ECMAScriptParser.propertyNameAndValueList(ECMAScriptParser.java:2622)
    at ECMAScriptParser.objectLiteral(ECMAScriptParser.java:2565)
    at ECMAScriptParser.singleExpression(ECMAScriptParser.java:3927)
    at ECMAScriptParser.expressionSequence(ECMAScriptParser.java:3075)
    at ECMAScriptParser.singleExpression(ECMAScriptParser.java:4211)
    at ECMAScriptParser.expressionSequence(ECMAScriptParser.java:3075)
    at ECMAScriptParser.expressionStatement(ECMAScriptParser.java:949)
    at ECMAScriptParser.statement(ECMAScriptParser.java:480)
    at ECMAScriptParser.sourceElement(ECMAScriptParser.java:366)
    at ECMAScriptParser.sourceElements(ECMAScriptParser.java:311)
    at ECMAScriptParser.program(ECMAScriptParser.java:255)
    at ECMAScriptProcessor.processJSFile(ECMAScriptProcessor.java:67)
    at ECMAScriptProcessor.walk(ECMAScriptProcessor.java:48)
    at ECMAScriptProcessor.main(ECMAScriptProcessor.java:33)
Caused by: org.antlr.v4.runtime.NoViableAltException
    at org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:1886)
    at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:486)
    at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:412)
    at ECMAScriptParser.propertyAssignment(ECMAScriptParser.java:2725)
    ... 14 more
```

For the first sight it seems that LT(1) in the rule of getter doesn't consume the 'get' keyword but the Identifier non-terminal does. However, nothing handles the upcoming 'b' identifier.

```
getter
 : {_input.LT(1).getText().startsWith("get")}? Identifier
 ;
```

Rewriting the rule as 

```
getter
 : {_input.LT(1).getText().equals("get")}? Identifier Identifier
 ;
```

solved the issue for me.

(Same goes for setters.)

**Comment by KvanTTT** [comment]
@renatahodovan , I guess, the more correct version looks like this (according to studied EcmaScript conent) :

```
getter
 : Get Identifier
 ;
```

And 'get' keyword should be added to lexer:
```
Get        : 'get';
```

Also it is important not to forget about the following rule:
```
PropertyName : AssignmentExpression
```
For handling this case 'get' keyword should be added to 'PropertyName' rule (according to [Object.defineProperty](http://robertnyman.com/javascript/javascript-getters-setters.html#object-defineproperty) syntax for example):
```
propertyName
 : identifierName
 | StringLiteral
 | numericLiteral
 | Get
 ;
```

The same actions should be performed for 'set' keyword.

**Comment by renatahodovan** [comment]
@KvanTTT: My concern with adding these new tokens is that it would prevent us from recognizing other Identifiers (like function or variable names) named as 'get' or 'set'.
On the other hand, I've also noticed that - according to ecma5 - the named part of getters/setters should be 'propertyName' instead of 'Identifier'.

So what do you think about something like this:

```
 getter
- : {_input.LT(1).getText().startsWith("get")}? Identifier
+ : {_input.LT(1).getText().equals("get")}? Identifier propertyName
  ;
 
 setter
- : {_input.LT(1).getText().startsWith("set")}? Identifier
+ : {_input.LT(1).getText().equals("set")}? Identifier propertyName
  ;
```

**Comment by KvanTTT** [comment]
@renatahodovan , maybe add Get and Set tokens to Identifier?

Identifier
 : IdentifierStart IdentifierPart*
 | Get
 | Set
 ;

**Comment by renatahodovan** [comment]
Adding Get and Set to the Identifier's alternatives would have no effect since these symbols are already covered by the `IdentifierStart IdentifierPart*` part. So they would be hidden.

This way, if we created these new lexer rules (Get/Set) then the 'get'/'set' symbols would be identifed either as Get/Set or as Identifier (based on the ordering of the lexer rules). Unfortunatelly, neither is a working solution: if Get/Set were defined earlier then function and variable names (with 'get'/'set') would fail since they expect an Identifier, otherwise - if Identifier were defined earlier - then getter/setter wouldn't be recognised, since they are expected to start with Get or Set tokens.

**Comment by KvanTTT** [comment]
This issue is a yet another argument for implementing [Token value comparison operator](https://github.com/antlr/antlr4/issues/1965).
