### ISSUE TITLE
swift grammar does not compile example "GameScene.swift"

### ISSUE THREAD

**Issue by teverett** [antlr/grammars-v4#238]
I've removed swift from the master compile until this is fixed.

<pre>
Parsing :/Users/tom/projects/grammars-v4/swift/examples/GameScene.swift
line 35:35 no viable alternative at input '2.0'
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.antlr.mojo.antlr4test.GrammarTestMojo.testGrammar(GrammarTestMojo.java:248)
	at org.antlr.mojo.antlr4test.GrammarTestMojo.testGrammars(GrammarTestMojo.java:275)
	at org.antlr.mojo.antlr4test.GrammarTestMojo.execute(GrammarTestMojo.java:120)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.antlr.v4.runtime.misc.ParseCancellationException
	at org.antlr.v4.runtime.BailErrorStrategy.recover(BailErrorStrategy.java:75)
	at SwiftParser.type(SwiftParser.java:11789)
	at SwiftParser.generic_argument(SwiftParser.java:2606)
	at SwiftParser.generic_argument_list(SwiftParser.java:2551)
	at SwiftParser.generic_argument_clause(SwiftParser.java:2506)
	at SwiftParser.primary_expression(SwiftParser.java:9753)
	at SwiftParser.postfix_expression(SwiftParser.java:11280)
	at SwiftParser.prefix_expression(SwiftParser.java:9380)
	at SwiftParser.expression(SwiftParser.java:9268)
	at SwiftParser.for_statement(SwiftParser.java:644)
	at SwiftParser.loop_statement(SwiftParser.java:552)
	at SwiftParser.statement(SwiftParser.java:396)
	at SwiftParser.statements(SwiftParser.java:495)
	at SwiftParser.code_block(SwiftParser.java:2972)
	at SwiftParser.function_body(SwiftParser.java:4800)
	at SwiftParser.function_declaration(SwiftParser.java:4517)
	at SwiftParser.declaration(SwiftParser.java:2715)
	at SwiftParser.declarations(SwiftParser.java:2823)
	at SwiftParser.declarations(SwiftParser.java:2829)
	at SwiftParser.declarations(SwiftParser.java:2829)
	at SwiftParser.declarations(SwiftParser.java:2829)
	at SwiftParser.declarations(SwiftParser.java:2829)
	at SwiftParser.declarations(SwiftParser.java:2829)
	at SwiftParser.declarations(SwiftParser.java:2829)
	at SwiftParser.class_body(SwiftParser.java:6555)
	at SwiftParser.class_declaration(SwiftParser.java:6470)
	at SwiftParser.declaration(SwiftParser.java:2736)
	at SwiftParser.statement(SwiftParser.java:380)
	at SwiftParser.top_level(SwiftParser.java:290)
	... 28 more
Caused by: org.antlr.v4.runtime.NoViableAltException
	at SwiftParser.type(SwiftParser.java:11696)
	... 55 more

</pre>

**Comment by teverett** [comment]
Removed the offending example files
