### ISSUE TITLE
[CSharp] Parsing source with syntax error causes ClassCastExceptin

### ISSUE THREAD

**Issue by yososs** [antlr/grammars-v4#2612]
I found this to be a cast error when entering the wrong C++ syntax into CSharp's parser.
This does not appear to be the correct way to handle syntax errors.

Sources containing syntax error
``` C#
class A{
  void a() {
    int[] nums = {1, 3, 5, 7};
    for (int num : nums){
        b(num);
    }
  }
}
```
Added the following cast check to avoid cast errors in CSharpParserBase.java.

``` C#
public abstract class CSharpParserBase extends Parser
{
    protected CSharpParserBase(TokenStream input)
    {
	super(input);
    }

    protected boolean IsLocalVariableDeclaration()
    {
   // fix
    if (!(this._ctx instanceof CSharpParser.Local_variable_declarationContext)) {
    	return false;
    }

	CSharpParser.Local_variable_declarationContext local_var_decl = (CSharpParser.Local_variable_declarationContext)this._ctx;
	if (local_var_decl == null) return true;
	CSharpParser.Local_variable_typeContext local_variable_type = local_var_decl.local_variable_type();
	if (local_variable_type == null) return true;
	if (local_variable_type.getText().equals("var")) return false;
	return true;
    }
}
```

~~However, it should be a syntax error, but it is not a syntax error.
Few people may consider this use case important.
Maybe it should be managed as a separate issue.~~

**Comment by kaby76** [comment]
The grammars-v4/csharp/ parser gives a syntax error for that input:

```
# run in Bash shell.
git clone https://github.com/antlr/grammars-v4.git
cd grammars-v4/csharp
trgen
cd Generated
make
cat - << HERE > test.in
class A{
  void a() {
    int[] nums = {1, 3, 5, 7};
    for (int num : nums){
        b(num);
    }
  }
}
HERE
dotnet run -file test.in
```
Output:
```
line 4:17 mismatched input ':' expecting ';'
Time: 00:00:00.1457023
Parse failed.
```

Please clarify what you are trying to do.

**Comment by yososs** [comment]
I am intentionally entering source code that results in a syntax error. The expected result is that CSharpParser reports a syntax error.

1. the actual result is that ClassCastException is thrown
2. if I fix this problem by adding a cast check, ~~no syntax error is reported~~

2 was an error in my method of syntax checking and was a pointing error.

To reproduce 1, follow the steps

You need to test on a java target.

1. save the above source in examples/test.cs
2. mvn3 test

```
line 4:17 mismatched input ':' expecting {'add', 'alias', '__arglist', 'ascending', 'async', 'await', 'by', 'descending', 'dynamic', 'equals', 'from', 'get', 'group', 'into', 'join', 'let', 'nameof', 'on', 'orderby', 'partial', 'remove', 'select', 'set', 'unmanaged', 'var', 'when', 'where', 'yield', IDENTIFIER, '[', '*', '?'}
com.khubla.antlr.antlr4test.AssertErrorsException: found 1 errors, but missing file test.cs.errors
	at com.khubla.antlr.antlr4test.AssertErrorsErrorListener.assertErrors(AssertErrorsErrorListener.java:64)
	at com.khubla.antlr.antlr4test.ScenarioExecutor.testGrammar(ScenarioExecutor.java:174)
	at com.khubla.antlr.antlr4test.ScenarioExecutor.testGrammars(ScenarioExecutor.java:229)
	at com.khubla.antlr.antlr4test.GrammarTestMojo.testScenarios(GrammarTestMojo.java:360)
	at com.khubla.antlr.antlr4test.GrammarTestMojo.execute(GrammarTestMojo.java:179)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:301)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:211)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:165)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:157)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:121)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:127)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:294)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.io.FileNotFoundException: /Users/yoshimoto/javaplatform/antlr/grammars-v4/csharp/examples/test.cs.errors (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:211)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:153)
	at com.khubla.antlr.antlr4test.FileUtil.getNonEmptyLines(FileUtil.java:91)
	at com.khubla.antlr.antlr4test.AssertErrorsErrorListener.assertErrors(AssertErrorsErrorListener.java:62)
```

**Comment by kaby76** [comment]
Got it. Yes, it doesn't work.

**Comment by yososs** [comment]
I am concerned about the different syntax error messages when run with dotnet and when run with java.

dotnet
> line 4:17 mismatched input ':' expecting ';'

java
> line 4:17 mismatched input ':' expecting {'add', 'alias', '__arglist', 'ascending', 'async', 'await', 'by', 'descending', 'dynamic', 'equals', 'from', 'get', 'group', 'into', 'join', 'let', 'nameof', 'on', 'orderby', 'partial', 'remove', 'select', 'set', 'unmanaged', 'var', 'when', 'where', 'yield', IDENTIFIER, '[', '*', '?'}

**Comment by kaby76** [comment]
I agree. I have a PR to fix the cast problem, but we'll need to find out why the diff in the runtimes.

**Comment by yososs** [comment]
Close this issue after confirming the merge.
