### ISSUE TITLE
Antlr4 Grammar does not work on the CPP Grammar

### ISSUE THREAD

**Issue by h4ck3rm1k3** [antlr/grammars-v4#272]
Attempting to parse the CPP14  grammar 

copy the cpp/CPP14.g4 into antlr4/examples/CPP14.g4
changed the pom to be verbose and print tree.
run mvn test
the output is here: 
antlr4/examples/CPP14.g4.err
https://github.com/h4ck3rm1k3/grammars-v4/commit/4cd2d16966fd422c0134fb9ebf9c20a92976df2e#diff-bfb944532751425acb6fcf0c7eeeb498

**Comment by teverett** [comment]
You are correct that the Antlr4 grammar doesn't part CPP14.g4.  Here is a more correct output from the failed test:

```
oscar:antlr4 tom$ mvn clean package
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.antlr.grammarsv4:antlr4:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.antlr:antlr4test-maven-plugin is missing. @ com.antlr.grammarsv4:antlr4:[unknown-version], /Users/tom/projects/grammars-v4/antlr4/pom.xml, line 41, column 12
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ANTLR4 grammar 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ antlr4 ---
[INFO] Deleting /Users/tom/projects/grammars-v4/antlr4/target
[INFO] 
[INFO] --- antlr4-maven-plugin:4.5.3:antlr4 (default) @ antlr4 ---
[INFO] ANTLR 4: Processing source directory /Users/tom/projects/grammars-v4/antlr4
[INFO] Processing grammar: ANTLRv4Lexer.g4
[INFO] Processing grammar: ANTLRv4Parser.g4
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ antlr4 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/tom/projects/grammars-v4/antlr4/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.0:compile (default-compile) @ antlr4 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 7 source files to /Users/tom/projects/grammars-v4/antlr4/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ antlr4 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/tom/projects/grammars-v4/antlr4/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.0:testCompile (default-testCompile) @ antlr4 ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ antlr4 ---
[INFO] No tests to run.
[INFO] 
[INFO] --- antlr4test-maven-plugin:1.3-SNAPSHOT:test (default) @ antlr4 ---
Parsing :/Users/tom/projects/grammars-v4/antlr4/examples/CPP14.g4
line 30:0 no viable alternative at input '/*******************************************************************************\n * C++14 Grammar for ANTLR v4\n *\n * Based on n4140 draft paper\n * https://github.com/cplusplus/draft/blob/master/papers/n4140.pdf\n * and\n * http://www.nongnu.org/hcb/\n * \n * Possible Issues:\n * \n * Input must avoid conditional compilation blocks (this grammar ignores any preprocessor directive)\n * GCC extensions not yet supported (not try parse preprocessor output)\n * Lexer issue with pure-specifier rule ('0' token) - Solution in embedded java\n * Right angle bracket (C++11) - Solution '>>' and '>>=' are not tokens, only '>'\n * \n ******************************************************************************/'
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.antlr.mojo.antlr4test.GrammarTestMojo.testGrammar(GrammarTestMojo.java:248)
	at org.antlr.mojo.antlr4test.GrammarTestMojo.testGrammars(GrammarTestMojo.java:275)
	at org.antlr.mojo.antlr4test.GrammarTestMojo.execute(GrammarTestMojo.java:120)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.antlr.v4.runtime.misc.ParseCancellationException
	at org.antlr.v4.runtime.BailErrorStrategy.recover(BailErrorStrategy.java:75)
	at org.antlr.parser.antlr4.ANTLRv4Parser.grammarType(ANTLRv4Parser.java:305)
	at org.antlr.parser.antlr4.ANTLRv4Parser.grammarSpec(ANTLRv4Parser.java:194)
	... 29 more
Caused by: org.antlr.v4.runtime.NoViableAltException
	at org.antlr.parser.antlr4.ANTLRv4Parser.grammarType(ANTLRv4Parser.java:298)
	... 30 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.771 s
[INFO] Finished at: 2016-05-04T19:01:39-06:00
[INFO] Final Memory: 24M/318M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.antlr:antlr4test-maven-plugin:1.3-SNAPSHOT:test (default) on project antlr4: Unable execute mojo: InvocationTargetException: ParseCancellationException: NoViableAltException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
oscar:antlr4 tom$ 

```

**Comment by teverett** [comment]
This is fixed, and CPP14.g4 is committed to the antlr4 examples
