### ISSUE TITLE
why left-recursive doesn't work

### ISSUE THREAD

**Issue by lewiscrow** [antlr/grammars-v4#2738]
the version of antlr4 is 4.0-complete.
here is my rule:
```
expr: expr '+' expr
    | expr '-' expr
    | ID
    ;
```
but when i try to process my java file, it shows:
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at org.antlr.v4.misc.OrderedHashMap.getElement(OrderedHashMap.java:46)
	at org.antlr.v4.analysis.LeftRecursiveRuleTransformer.setAltASTPointers(LeftRecursiveRuleTransformer.java:241)
	at org.antlr.v4.analysis.LeftRecursiveRuleTransformer.translateLeftRecursiveRule(LeftRecursiveRuleTransformer.java:162)
	at org.antlr.v4.analysis.LeftRecursiveRuleTransformer.translateLeftRecursiveRules(LeftRecursiveRuleTransformer.java:89)
	at org.antlr.v4.semantics.SemanticPipeline.process(SemanticPipeline.java:94)
	at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:399)
	at org.antlr.v4.Tool.process(Tool.java:384)
	at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:343)
	at org.antlr.v4.Tool.main(Tool.java:190)
```
and the exception disappeared when i change the rule to:
```
expr: '+' expr
    | '-' expr
    | ID
    ;
```
i wonder why it happened and how  i can solve it.
thx

**Comment by lewiscrow** [comment]
the problem is solved when i changed the tool version 4.0-complete to 4.2.0-complete...
but why didn't i see this fix in history issues?
