### ISSUE TITLE
[PLSQL java target] Java heap space error

### ISSUE THREAD

**Issue by wegoodwin** [antlr/grammars-v4#2791]
I decided to run a test on the PLSQL grammar that has about 9000 insert statements.  When I try to build a parse tree I get the following error:

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.lang.Integer.toString(Integer.java:401)
	at java.lang.String.valueOf(String.java:3099)
	at plsqlparser.PLSQLListner.exitEveryRule(PLSQLListner.java:145)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:63)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:38)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at plsqlparser.PLSQLCodeReview.buildSRCAST(PLSQLCodeReview.java:122)
	at plsqlparser.PLSQLCodeReview.start(PLSQLCodeReview.java:50)
	at CreateAST.main(CreateAST.java:111)

If I take the number of records in the file down to about 1000 it seems to work fine.  Any help would be greatly appreciated.

[LargeTest.log](https://github.com/antlr/grammars-v4/files/9469358/LargeTest.log)

**Comment by Commodore68** [comment]
In my experience with it, you have two options as it now. 

1. increase the heap size for Java when you run the parser
2. reduce the size of each file you pass in like you already did.

**Comment by wegoodwin** [comment]
I was able to increase the size of the heap and reduce the size of the file to get around the issue.  It just seems like such a strange thing to have to do to process 10K lines of code.
________________________________

**Comment by KvanTTT** [comment]
Have you tried to use parse tree free processing strategy? It allows creating AST during parsing without creating full parse tree.

**Comment by wegoodwin** [comment]
Hi Ivan,

How do I do this?  I've not heard of this.
________________________________

**Comment by KvanTTT** [comment]
ANTLR generates Parse Tree instead of AST, but the latest also can be generated by hand without generating Parse Tree using listeners and bottom-up AST building. See [PlSqlAntlrListenerConverter](https://github.com/KvanTTT/PT.PM/blob/dev/Sources/PT.PM.PlSqlParseTreeUst/PlSqlAntlrListenerConverter.cs) for example. To skip Parse Tree building, the option `BuildParseTree` should be set up to `false`.

Such an approach may reduce memory pressure and improve performance especially for huge files (1KK lines) because in general, AST has much fewer nodes than Parse Tree.

In my opinion, it's an underestimated piece of advice about performance because I've never read about it in ANTLR articles.

**Comment by wegoodwin** [comment]
OK,

Thanks.  I will research this.
________________________________
