### ISSUE TITLE
php grammar: Java target crashes on tests when printing trees

### ISSUE THREAD

**Issue by kaby76** [antlr/grammars-v4#3017]
The [php]() grammar crashes when trying to print out trees (`trgen -t Java; cd Generated-Java; make; make test`).
```
Exception in thread "main" java.lang.NullPointerException
        at org.antlr.v4.runtime.misc.Utils.escapeWhitespace(Utils.java:63)
        at org.antlr.v4.runtime.tree.Trees.toStringTree(Trees.java:49)
        at org.antlr.v4.runtime.tree.Trees.toStringTree(Trees.java:58)
        at org.antlr.v4.runtime.tree.Trees.toStringTree(Trees.java:58)
        at org.antlr.v4.runtime.tree.Trees.toStringTree(Trees.java:58)
        at org.antlr.v4.runtime.tree.Trees.toStringTree(Trees.java:58)
        at org.antlr.v4.runtime.tree.Trees.toStringTree(Trees.java:58)
        at org.antlr.v4.runtime.tree.Trees.toStringTree(Trees.java:42)
        at org.antlr.v4.runtime.RuleContext.toStringTree(RuleContext.java:189)
        at Test.DoParse(Test.java:206)
        at Test.ParseFilename(Test.java:135)
        at Test.main(Test.java:107)
```
The code crashes because a [token is created with no text](https://github.com/antlr/grammars-v4/blob/56dcd3d9251506d7514a68e86a4c192735c48f59/php/Java/PhpLexerBase.java#L75), whereas in other targets, text is assigned ([Python3](https://github.com/antlr/grammars-v4/blob/56dcd3d9251506d7514a68e86a4c192735c48f59/php/Python3/PhpLexerBase.py#L64), [JavaScript](https://github.com/antlr/grammars-v4/blob/56dcd3d9251506d7514a68e86a4c192735c48f59/php/JavaScript/PhpLexerBase.js#L64)). Why the Antlr API allows one to create a CommonToken that is basically inconsistent (null text field, unknow values for start and stop, etc.) is dubious. That, or the toStringTree() API should NOT crash on null pointers!

Note, the CSharp target does not create a new token, but [assigns the type without setting text](https://github.com/antlr/grammars-v4/blob/56dcd3d9251506d7514a68e86a4c192735c48f59/php/CSharp/PhpLexerBase.cs#L83). There's a [Python](https://github.com/antlr/grammars-v4/tree/master/php/Python) directory, but there is no such thing as a "Python" target--only Python2 or Python3--and the code diverges between Python/ and Python3 ever so slightly, too.

It's a hot steamy mess everywhere you look.

**Comment by RossPatterson** [comment]
This is ANTLR bug #[2677](https://github.com/antlr/antlr4/issues/2677), originally opened on 2019-10-26.  I ran into it during my work to improve parse-tree- and errors-file testing, and verified that it was still a bug as of ANTLR4 4.11.1.
