### ISSUE TITLE
PostgreSQL Grammar is not working

### ISSUE THREAD

**Issue by jwalton922** [antlr/grammars-v4#3315]
There seems to be a problem with the PostgreSQL grammar. The python generated parser for PosgreSQL does not work. 

The command: 

`antlr4 -Dlanguage=Python3 PostgreSQLLexer.g4`

results in warnings:

```
warning(146): PostgreSQLLexer.g4:3000:0: non-fragment lexer rule AfterEscapeStringConstantMode_NotContinued can match the empty string
warning(146): PostgreSQLLexer.g4:3019:0: non-fragment lexer rule AfterEscapeStringConstantWithNewlineMode_NotContinued can match the empty string
```

The generated Python class will not run due to syntax errors. A non-python comment is in the class:
```
Traceback (most recent call last):
  File "...py", line 3, in <module>
    from PostgreSQLLexer import PostgreSQLLexer
  File "...PostgreSQLLexer.py", line 3734
    /* This field stores the tags which are used to detect the end of a dollar-quoted string literal.
    ^
SyntaxError: invalid syntax
```
With that comment removed, there are indentation errors starting with some empty if blocks. I didn't attempt to fix those.

I also tried out using the lab: http://lab.antlr.org/. When selecting PostgreSQL and attempting to run it against any SQL just returns the same warnings above.

**Comment by kaby76** [comment]
There's no port of the sql/postgresql/ base classes to Python3. Only [CSharp and Java](https://github.com/antlr/grammars-v4/blob/22ba8de514996291c6e951f698988d83b7d968aa/sql/postgresql/desc.xml#L4) work. Neither lab.antlr.org nor the Intellij Antlr plugin will work on this grammar because it contains actions, e.g., [here](https://github.com/antlr/grammars-v4/blob/22ba8de514996291c6e951f698988d83b7d968aa/sql/postgresql/PostgreSQLLexer.g4#L181), because action code is not compiled to the target. The `non-fragment lexer rule ... can match the empty string` warning means that the grammar is incorrect. At some point, this will have to be fixed.

**Comment by jwalton922** [comment]
Thanks for the quick response! We will look into using those languages.

Should I close this issue?

**Comment by kaby76** [comment]
I guess leave it open. It functions as an item on the "to do" list of things to fix.
