### ISSUE TITLE
PL/SQL: support COUNT(*) in PIVOT elements

### ISSUE THREAD

**Issue by danlyons-softek** [antlr/grammars-v4#3823]
I ran into some parse failures with a query including a `PIVOT` using `COUNT(*)`.  I can reproduce it with the following simplistic query against v$session:
```sql
WITH SessionCTE AS
(
    SELECT
        terminal
    FROM v$session
)
SELECT
    *
FROM SessionCTE
PIVOT
(
    COUNT(*) FOR terminal IN ('VIRTUALORACLE11' AS oracle_local, 'DRUID' AS druid, 'THOR' AS thor)
)
```
which executes successfully on my ancient 11.2.0.1 Oracle test instance:
ORACLE_LOCAL|DRUID|THOR
|---:|---:|---:|
23|2|2

For reference: [Oracle pivot_clause documentation](https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/SELECT.html#GUID-CFA006CA-6FF1-4972-821E-6996142A51C6__CHDCEJJE)

The current parser definition for `pivot_element` is as follows:
https://github.com/antlr/grammars-v4/blob/d939aad7310b6a214d6ade30afc90eb28f9fe809/sql/plsql/PlSqlParser.g4#L5735-L5737

At a glance, it looks like it _should_ work with `COUNT(*)`, but it fails with the following:
Exception:
```stacktrace
Antlr4.Runtime.InputMismatchException: Exception of type 'Antlr4.Runtime.InputMismatchException' was thrown.
   at Antlr4.Runtime.DefaultErrorStrategy.Sync(Parser recognizer)
   at extracttables.Grammars.PlSqlParser.sql_script() in c:\repository\panther\src\database\code\build\extracttables\obj\Debug\PlSqlParser.cs:line 2311
```
Message: `mismatched input '(' expecting {<EOF>, '/', ';'}`
Offending Symbol: `mismatched input '(' expecting {<EOF>, '/', ';'}`
Line: 11
Character Position: 0

**Comment by danlyons-softek** [comment]
For my immediate purposes, I switched `pivot_element` locally to the following:
```diff
pivot_element
---    : aggregate_function_name '(' expression ')' column_alias?
+++    : numeric_function column_alias?
    ;
```
referencing:
https://github.com/antlr/grammars-v4/blob/d939aad7310b6a214d6ade30afc90eb28f9fe809/sql/plsql/PlSqlParser.g4#L6354-L6362

but I'm not sure that's quite correct.
