### ISSUE TITLE
ModuleNotFoundError: No module named 'JavaLexerBase'

### ISSUE THREAD

**Issue by yamin8000** [antlr/grammars-v4#3868]
```
~\python.exe ~\IdeaProjects\antlr\main.py 
Traceback (most recent call last):
  File "~\IdeaProjects\antlr\main.py", line 4, in <module>
    from java20.Java20Lexer import Java20Lexer
  File "!\IdeaProjects\antlr\java20\Java20Lexer.py", line 12, in <module>
    from .JavaLexerBase import JavaLexerBase
ModuleNotFoundError: No module named 'java20.JavaLexerBase'
```

**Comment by kaby76** [comment]
You don't generate the JavaLexerBase class. The port to Python3 of the [java20 grammar](https://github.com/antlr/grammars-v4/tree/master/java/java20) has not been done.

**Comment by yamin8000** [comment]
> You don't generate the JavaLexerBase class. The port to Python3 of the [java20 grammar](https://github.com/antlr/grammars-v4/tree/master/java/java20) has not been done. I had time only to write [Cpp, CSharp, Dart, Java](https://github.com/antlr/grammars-v4/blob/88d1596e23eba3bcd9d8c159e90fce653f323986/java/java20/desc.xml#L3) ports. So, you will need to write that if you need it now.

Thanks for your advice.
Currently, I'm using Java as my base for porting to Python. I don't seem to understand where the `Character` class comes from.

**Comment by yamin8000** [comment]
> You don't generate the JavaLexerBase class. The port to Python3 of the [java20 grammar](https://github.com/antlr/grammars-v4/tree/master/java/java20) has not been done. I had time only to write [Cpp, CSharp, Dart, Java](https://github.com/antlr/grammars-v4/blob/88d1596e23eba3bcd9d8c159e90fce653f323986/java/java20/desc.xml#L3) ports. So, you will need to write that if you need it now.

#3870
