### ISSUE TITLE
Errors running C++ and C# lexers

### ISSUE THREAD

**Issue by Logopher** [antlr/grammars-v4#4059]
Running the example from the tutorial (Expr.g4) works fine, but these are giving the same typecasting exception. Am I missing part of the toolchain...?

EDIT: I had initially downloaded only the lexer and parser grammars. Looking into the listed code, I noticed that the idea of a "combined grammar" is mentioned. I gave the C++ and C# grammars each their own folder with all the other contents of the respective repo folders, and I'm still getting the same error.

```
{user}\Documents>antlr4-parse CPP14Lexer.g4 -tokens -trace
Exception in thread "main" java.lang.ClassCastException: class org.antlr.v4.gui.Interpreter$IgnoreTokenVocabGrammar cannot be cast to class org.antlr.v4.tool.LexerGrammar (org.antlr.v4.gui.Interpreter$IgnoreTokenVocabGrammar and org.antlr.v4.tool.LexerGrammar are in unnamed module of loader 'app')
        at org.antlr.v4.semantics.SymbolChecks.checkForModeConflicts(SymbolChecks.java:313)
        at org.antlr.v4.semantics.SemanticPipeline.process(SemanticPipeline.java:110)
        at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:371)
        at org.antlr.v4.Tool.process(Tool.java:359)
        at org.antlr.v4.tool.Grammar.<init>(Grammar.java:364)
        at org.antlr.v4.gui.Interpreter$IgnoreTokenVocabGrammar.<init>(Interpreter.java:42)
        at org.antlr.v4.gui.Interpreter.interp(Interpreter.java:141)
        at org.antlr.v4.gui.Interpreter.main(Interpreter.java:277)

{user}\Documents>antlr4-parse CSharpLexer.g4 -tokens -trace
Exception in thread "main" java.lang.ClassCastException: class org.antlr.v4.gui.Interpreter$IgnoreTokenVocabGrammar cannot be cast to class org.antlr.v4.tool.LexerGrammar (org.antlr.v4.gui.Interpreter$IgnoreTokenVocabGrammar and org.antlr.v4.tool.LexerGrammar are in unnamed module of loader 'app')
        at org.antlr.v4.semantics.SymbolChecks.checkForModeConflicts(SymbolChecks.java:313)
        at org.antlr.v4.semantics.SemanticPipeline.process(SemanticPipeline.java:110)
        at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:371)
        at org.antlr.v4.Tool.process(Tool.java:359)
        at org.antlr.v4.tool.Grammar.<init>(Grammar.java:364)
        at org.antlr.v4.gui.Interpreter$IgnoreTokenVocabGrammar.<init>(Interpreter.java:42)
        at org.antlr.v4.gui.Interpreter.interp(Interpreter.java:141)
        at org.antlr.v4.gui.Interpreter.main(Interpreter.java:277)
```

**Comment by kaby76** [comment]
The grammars are fine. The problem is that you cannot use the "antlr interpreter" for these grammars. You know it's an interpreter because it didn't have any options to use a specific target.

Any grammar that contains "actions" therefore contains target-specific code (i.e., Java, or C#, or C++, or Dart, or ...), and therefore requires running the "Antlr tool" (antlr4) with the `-Dlanguage=...." option to generate the parser for the target. You then need to build the parser for the target, i.e., compile .cpp files into an executable.

By convention, a grammar in grammars-v4 that contains a directory named after the target means that you need to use the Antlr tool and build a program. For the [cpp](https://github.com/antlr/grammars-v4/tree/master/cpp) and [csharp](https://github.com/antlr/grammars-v4/tree/master/csharp) grammars, you will see directories named after the target. E.g., [for the Dart target](https://github.com/antlr/grammars-v4/tree/master/cpp/Dart) with the cpp grammar. The desc.xml contains a `<targets>` element that describes what targets are supported. E.g., [the Dart target for the cpp grammar](https://github.com/antlr/grammars-v4/blob/b019c956c3405ebcb7d78f38ee9a902c598519ef/cpp/desc.xml#L3C24-L3C28).

The description for this repo, grammars-v4, is "Grammars written for ANTLR v4; expectation that the grammars are free of actions", but it wrong. There can be actions, but generally they are only "semantic predicates".

To test whether a grammar contains actions or semantic predicates, which then means that it has target-specific code, can be determined by examining the grammar. For example, with the cpp grammar, [we see a semantic predicate](https://github.com/antlr/grammars-v4/blob/b019c956c3405ebcb7d78f38ee9a902c598519ef/cpp/CPP14Parser.g4#L825C11-L825C45) in the `memberDeclarator` rule of the parser grammar. You can either inspect the grammar manually, searching for "}?", or use the [Trash toolkit](https://github.com/kaby76/Domemtech.Trash) and the [find-semantic-predicate.sh](https://github.com/kaby76/g4-scripts/blob/c01e746656bf93b387063503ef9c01296bafa9e4/find-semantic-predicate.sh) script.

If you want to build a parser for these target specific grammars, you need to copy the target-specific files into the directory containing the .g4's, and write a driver program there. Or, you can use the [trgen tool of Trash](https://github.com/kaby76/Domemtech.Trash/tree/main/src/trgen) to automatically generate a complete program for the target.

**Comment by Logopher** [comment]
Thanks very much for the explanation.
