### ISSUE TITLE
[Pl/Sql] Fails to run tests

### ISSUE THREAD

**Issue by Naros** [antlr/grammars-v4#4352]
After pulling the most recent changes from master using:
```
git pull upstream master
```
I change into the plsql directory and attempt to run the tests using:
```
cd sql/plsql
mvn clean test
```
This immediately fails when trying to parse the SQL files, as follows:
```
[INFO] --- antlr4test:1.22:test (default) @ plsql ---
[INFO] Evaluating Scenario: Default Scenario
[INFO] Parsing :/home/ccranfor/github/Naros/grammars-v4/sql/plsql/examples/administer_key_management.sql
line 2:0 mismatched input 'TO' expecting 'TO'
line 100:4 mismatched input ''AW5z3CoyKE/yv3cNT5CWCXUAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'' expecting <EOF>
com.khubla.antlr.antlr4test.AssertErrorsException: found 2 errors, but missing file administer_key_management.sql.errors
        at com.khubla.antlr.antlr4test.AssertErrorsErrorListener.assertErrors(AssertErrorsErrorListener.java:64)
        at com.khubla.antlr.antlr4test.ScenarioExecutor.testGrammar(ScenarioExecutor.java:174)
        at com.khubla.antlr.antlr4test.ScenarioExecutor.testGrammars(ScenarioExecutor.java:229)
        at com.khubla.antlr.antlr4test.GrammarTestMojo.testScenarios(GrammarTestMojo.java:360)
        at com.khubla.antlr.antlr4test.GrammarTestMojo.execute(GrammarTestMojo.java:179)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
        at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
        at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
        at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:903)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:280)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:203)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:255)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:201)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:361)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:314)
Caused by: java.io.FileNotFoundException: /home/ccranfor/github/Naros/grammars-v4/sql/plsql/examples/administer_key_management.sql.errors (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
        at com.khubla.antlr.antlr4test.FileUtil.getNonEmptyLines(FileUtil.java:91)
        at com.khubla.antlr.antlr4test.AssertErrorsErrorListener.assertErrors(AssertErrorsErrorListener.java:62)
        ... 29 more
```

java 21.0.4 2024-07-16 LTS
Java(TM) SE Runtime Environment (build 21.0.4+8-LTS-274)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.4+8-LTS-274, mixed mode, sharing)

Apache Maven 3.9.8 (36645f6c9b5079805ea5009217e36f2cffd34256)
Maven home: /opt/maven/latest
Java version: 21.0.4, vendor: Oracle Corporation, runtime: /opt/java/jdk-21.0.4
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.11.5-200.fc40.x86_64", arch: "amd64", family: "UNIX"

Can anyone explain why the PLSQL test suite refuses to parse the SQL files? Is there a parser bug problem or is this is something related to something else?  If I run the MariaDB or MySQL grammars, these work fine, so this makes me question if the upstream grammar is borked.  I should note, this is with no local changes, just what is in the master branch as of now.

Is there something specific about my environment that prevents running the tests?

**Comment by Naros** [comment]
Looks to have been some previous cache issue with the grammar where `mvn clean` was not actually cleaning up references and this created an issue.

**Comment by kaby76** [comment]
Actually, `mvn clean test` is broken for the ["Official MySQL grammar,"](https://github.com/antlr/grammars-v4/tree/b411201e8375764663ec758ba15f9bf40b852013/sql/mysql/Oracle) not the hacked Positive-Technologies grammar, which will become obsolete at some point. Fixing.
