### ISSUE TITLE
Java8.g gives ParseError on generated Java8Parser

### ISSUE THREAD

**Issue by mscinar** [antlr/grammars-v4#485]
Hi, I'm new to ANTLR and wanted to do some java-sourcecode analysis with the Java8.g-grammar. Unfortunately the generated Java8Parser.java is not parsed by the antlr parser itself, and I can't see what the problem is, because my IDE shows no errors and I can't see any obvious error. (I have used the parser on several sourcecode files from apache project releases and there were also some parse errors). 
The parsed Java8parser.java is attached. It's the plain generated file. I used antlr4-maven-plugin 4.5 and antlr4-runtime 4.5.3.

[Java8Parser.java.txt](https://github.com/antlr/grammars-v4/files/493807/Java8Parser.java.txt)

`org.antlr.v4.runtime.misc.ParseCancellationException: offending symbol: [@2512,18234:18234=')',<58>,236:44]line 236:44 extraneous input ')' expecting {'++', '--'}, e=null
	at de.cinarconsulting.antlr4.ThrowingErrorListener.syntaxError(ThrowingErrorListener.java:24) ~[classes/:?]
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:65) ~[antlr4-runtime-4.5.3.jar:4.5.3]
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:564) ~[antlr4-runtime-4.5.3.jar:4.5.3]
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportUnwantedToken(DefaultErrorStrategy.java:375) ~[antlr4-runtime-4.5.3.jar:4.5.3]
	at org.antlr.v4.runtime.DefaultErrorStrategy.sync(DefaultErrorStrategy.java:273) ~[antlr4-runtime-4.5.3.jar:4.5.3]
	at de.cinarconsulting.antlr4.Java8Parser.postfixExpression(Java8Parser.java:17956) ~[classes/:?]
	at de.cinarconsulting.antlr4.Java8Parser.postIncrementExpression(Java8Parser.java:18002) ~[classes/:?]
	at de.cinarconsulting.antlr4.Java8Parser.statementExpression(Java8Parser.java:9935) ~[classes/:?]
	at de.cinarconsulting.antlr4.Java8Parser.statementExpressionList(Java8Parser.java:11199) ~[classes/:?]
	at de.cinarconsulting.antlr4.Java8Parser.forUpdate(Java8Parser.java:11151) ~[classes/:?]
	at de.cinarconsulting.antlr4.Java8Parser.basicForStatement(Java8Parser.java:10950) ~[classes/:?]
	at de.cinarconsulting.antlr4.Java8Parser.forStatement(Java8Parser.java:10798) ~[classes/:?]
	at de.cinarconsulting.antlr4.Java8Parser.statement(Java8Parser.java:9390) ~[classes/:?]
	at de.cinarconsulting.antlr4.Java8Parser.blockStatement(Java8Parser.java:9175) ~[classes/:?]
	at de.cinarconsulting.antlr4.Java8Parser.blockStatements(Java8Parser.java:9102) ~[classes/:?]
	at de.cinarconsulting.antlr4.Java8Parser.block(Java8Parser.java:9041) ~[classes/:?]
	at de.cinarconsulting.antlr4.Java8Parser.staticInitializer(Java8Parser.java:6188) ~[classes/:?]
	at de.cinarconsulting.antlr4.Java8Parser.classBodyDeclaration(Java8Parser.java:3642) ~[classes/:?]
	at de.cinarconsulting.antlr4.Java8Parser.classBody(Java8Parser.java:3564) ~[classes/:?]
	at de.cinarconsulting.antlr4.Java8Parser.normalClassDeclaration(Java8Parser.java:3140) ~[classes/:?]
	at de.cinarconsulting.antlr4.Java8Parser.classDeclaration(Java8Parser.java:3025) ~[classes/:?]
	at de.cinarconsulting.antlr4.Java8Parser.typeDeclaration(Java8Parser.java:2959) ~[classes/:?]
	at de.cinarconsulting.antlr4.Java8Parser.compilationUnit(Java8Parser.java:2483) ~[classes/:?]
	at de.cinarconsulting.data.JavaToTokenMain.processJava(JavaToTokenMain.java:119) [classes/:?]
	at de.cinarconsulting.data.JavaToTokenMain.processFile(JavaToTokenMain.java:55) [classes/:?]
	at de.cinarconsulting.data.JavaToTokenMain.process(JavaToTokenMain.java:32) [classes/:?]`

**Comment by teverett** [comment]
Can we see your code that is trying to do this?  The validation suite for grammars-v4 does exactly what you are having trouble with; parses every grammar on the tree, and then runs that grammar against any example files in the /examples/ directory.  You can see the code that does the parse here:

[https://github.com/teverett/antlr4test-maven-plugin/blob/master/src/main/java/com/khubla/antlr/antlr4test/GrammarTestMojo.java](https://github.com/teverett/antlr4test-maven-plugin/blob/master/src/main/java/com/khubla/antlr/antlr4test/GrammarTestMojo.java)

Look for the method "testGrammar".

You can see the latest results of running the validation suite on Travis here:

[https://s3.amazonaws.com/archive.travis-ci.org/jobs/162145983/log.txt](https://s3.amazonaws.com/archive.travis-ci.org/jobs/162145983/log.txt)

If you search for "Building Java8 grammar 1.0-SNAPSHOT" you will see that the grammar did parse, that .class files were created and that the grammar did run against "helloworld.java".

**Comment by mscinar** [comment]
Hi dear Tom,
attached is my project, containing the class "JavaToTokenMain", which itself calls the Parser generated by the maven plugin and the grammar.
The main action looks like this:
`        try {
            Lexer lexer = new Java8Lexer(new ANTLRInputStream(in));
            lexer.removeErrorListeners();
            lexer.addErrorListener(de.cinarconsulting.neurocoder.antlr4.ThrowingErrorListener.INSTANCE);
            CommonTokenStream tokens = new CommonTokenStream(lexer);

            Java8Parser parser = new Java8Parser(tokens);
            parser.removeErrorListeners();
            parser.addErrorListener(de.cinarconsulting.neurocoder.antlr4.ThrowingErrorListener.INSTANCE);
//        parser.setErrorHandler(new BailErrorStrategy());
            parser.setBuildParseTree(true);
            parser.getInterpreter().setPredictionMode(PredictionMode.SLL);

            // start parsing at the compilationUnit rule
            ParserRuleContext t = parser.compilationUnit();
            System.out.println(t.toStringTree(parser));
        } catch (Exception e) {
            throw new ParseException(e);
        }`
As denoted, it works on some files. Perhaps my setup is flawed? 
[neurocoder copy.zip](https://github.com/antlr/grammars-v4/files/496069/neurocoder.copy.zip)

**Comment by teverett** [comment]
ok, I have built a project that shows successful compile of Java8Parser.g4 to Java code, and then use of that Java code to parse Java8Parser.g4.  The project is here:

https://github.com/teverett/antlrparseexample

**Comment by mscinar** [comment]
Hi dear Tom, 
thank you very much for your fast support and providing me an example! That helps me a lot.
Do you have any clue why my setup didn't work? I mean it seems like the maven plugin generated a valid compilabe parser, which seems to have problems with very basic structures.
